#!/usr/bin/env python
import sys
import json
import struct

text_length_bytes = sys.stdin.read(4).encode('utf-8')

if len(text_length_bytes) == 0:
		sys.stderr.write("no message sent")
		sys.exit(1)

text_length = struct.unpack('i', text_length_bytes)[0]
print(text_length)

rawJSON = sys.stdin.read(text_length);
text = json.loads(rawJSON)['text']
tempFile = open('/home/ianrtaylor/test', 'w')
tempFile.write(text)
