#!/usr/bin/env python
import sys
import json
import struct

VERSION = "0.1"

if len(sys.argv) > 1:
		if sys.argv[1] == "--version":
			print(VERSION)
			sys.exit(0)
		else:
			sys.exit(1)

text_length_bytes = sys.stdin.read(4).encode('utf-8')

if len(text_length_bytes) == 0:
		sys.stderr.write("no message sent")
		sys.exit(1)

text_length = struct.unpack('i', text_length_bytes)[0]

JSON = json.loads(sys.stdin.read(text_length))
text = JSON['text']
path = JSON['path']

tempFile = open(path, 'w')
tempFile.write(text)
